### ISSUE TITLE
database schema is missing 

### ISSUE THREAD

**Issue by Sak1s** [socioboard/socioboard#13]
database schema is missing ...

**Comment by socioboard** [comment]
Hi There,

Its done, please check.

Best regards,
Support Team
Socioboard Technologies Pvt. Ltd.
<http://www.socioboard.com>

*Bangalore Office:* L V Complex, 2nd Floor, No.58, 7th Block, 80 Feet 
Road, Koramangala Bangalore 560095 Karnataka, India
*
Phone:* +91-90090-23807, *Skype:* socioboard.support

Socioboard Enterprise and SaaS Versions: http://www.socioboard.com
Socioboard Community Version: http://www.socioboard.org

”Facebook” <https://www.facebook.com/SocioBoard> 	G+ 
<https://plus.google.com/s/socioboard> 	”LinkedIn” 
<http://www.linkedin.com/company/socioboard> 	”Twitter” 
<https://twitter.com/Socioboard>

**Comment by netun0** [comment]
Hi,

There's also a lot of files missing, the master release is broken! Please, someone more would confirm?

**Comment by Sak1s** [comment]
how i can access AdminHome

i insert in Admin table some data but i coun not access admin panel

  if (ObjUser.ProfileUrl != null && ObjUser.ProfileUrl != "")

**Comment by Sak1s** [comment]
table schema is missing some columns  in user table , like ChangeEmailKey and IsEmailKeyUsed

**Comment by socioboard** [comment]
Updated the repo with new schema, please check now :)

**Comment by socioboard** [comment]
Please Download the new release and check
https://github.com/socioboard/socioboard/releases/tag/v2.0.6

**Comment by Sak1s** [comment]
still have problem with the adminhome. 
I create a record in Admin table , user:admin , pass admin and i got stille the following error

Line 100:                        
Line 101:                        @{
Line 102:                            if (ObjUser.ProfileUrl != null && ObjUser.ProfileUrl != "")
Line 103:                            {
Line 104:

**Comment by socioboard** [comment]
Hi
Please check this video if any log4net issue occurs
http://screencast.com/t/lxrzSJJBK

**Comment by socioboard** [comment]
Hi there,

#still have problem with the adminhome. 
For this you need to make the UserType in User table as SuperAdmin

**Comment by socioboard** [comment]
Please refer to the latest release https://github.com/socioboard/socioboard/releases/tag/v2.0.7
Also please read the comment there with videos
Regards
Socioboard Support
