### ISSUE TITLE
SocioBoardDataServices in 2.0.9

### ISSUE THREAD

**Issue by Sak1s** [socioboard/socioboard#17]
I am facing the following problem when open the project with VS

The project 'SocioBoardDataServices' cannot be added to the solution because a project with the same filename already exists in the solution

C:\SocioBoard\SocioBoard\SocioboardDataServices\SocioboardDataServices.csproj : error  : The project file could not be loaded. Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 616, position 2.  C:\SocioBoard\SocioBoard\SocioboardDataServices\SocioboardDataServices.csproj

**Comment by Sak1s** [comment]
This line of code is repeated alot of time in the code 
"<<<<<<< HEAD"
also this one 
">>>>>>> b359b54c5e7811194d1e3c4e7694ccd632caa3ef"

**Comment by redknitin** [comment]
@Sak1s That indicates the version control software identified conflicts and couldn't automatically merge the code with the latest in the repository. Manual merging of the code needs to be performed (or you can drop changes from one of the two).
